app:
    useFakeCustomerRepo: false
info:
    app:
        description: Porno
        name: Pekkas Porn App (PROD)
        version: 1.0
logging:
    charset:
        file: utf8
    file:
        name: app.log
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: never
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: admin
        url: jdbc:h2:mem:testdb-dev-env
        username: dev
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
